<?php


namespace App\Constants\Payments;


class DepositInfo
{
    PUBLIC CONST BANK_NAME = 1;
    PUBLIC CONST ACCT_FN = 2;
    PUBLIC CONST ACCT_LN = 3;
    PUBLIC CONST ACCT_NO = 4;
    PUBLIC CONST IFSC =5;
    PUBLIC CONST AMOUNT =6;
    PUBLIC CONST BANK_NAME_INPUT =7;
    PUBLIC CONST ACCT_NAME=8;
    publIC CONST TXN_TIME=9;
    PUBLIC CONST UPLOAD_TXN  =10;
    PUBLIC CONST CRYPTO_AMOUNT = 11;
    PUBLIC CONST NETWORK=12;
    PUBLIC CONST ADDRESS =13;
    PUBLIC CONST QR_CODE =14;
    PUBLIC CONST TXID=15;
    PUBLIC CONST DEPOSIT_AMOUNT =16;
    PUBLIC CONST BANK_NAME_FOR_CARD =17;
    PUBLIC CONST CARD_NUMBER=18;
    PUBLIC CONST MOBILE_NUMBER=19;
    PUBLIC CONST ACCOUNT_ID=20;
    PUBLIC CONST EMAIL=21;
}
